### PR TITLE
Check modifications in contracts before add/upgrade proxy

### LINKED ISSUE #22: Remind the user to sync the current package state before managing proxies
If a user runs an `add-implementation` and attempts to create a proxy for it **before** running `sync`, the CLI will fail with a not-found error. Or, even worse, since the backing implementation is the same as it was not upgraded, the [proxy itself](https://github.com/zeppelinos/zos-lib/blob/master/contracts/upgradeability/UpgradeabilityProxy.sol#L59) will fail to upgrade with a VM revert.

Remind the user to sync the current package state to the blockchain before creating or upgrading a proxy.

### PR DESCRIPTION
**Pull request by spalladino**
This PR adds to the network package.zos file the bytecode of the
contract at the time it was deployed. It is then compared to the
bytecode of the contract locally before creating or upgrading a
proxy. If there was a change, then the command fails; this can be
overridden via a --force flag to either command.

Fixes #22.

### CODE REVIEW

**Comment by spalladino** [comment]
Note that this requires the contracts to *have been compiled* in order to detect any changes. Analyzing the source code file does not work, since a contract may inherit from a contract imported from another file; so even if the source of the file stays the same, the resulting bytecode may change.

File: src/models/NetworkAppController.js [hunk 1]
```diff
@@ -132,13 +136,16 @@ export default class NetworkAppController {
...
+    // TODO: Store the implementation's hash or full source/byte code to avoid unnecessary deployments
     return Promise.all(_.map(this.package.contracts, async (contractName, contractAlias) => {
       const contractClass = ContractsProvider.getFromArtifacts(contractName);
       log.info(`Uploading ${contractName} implementation for ${contractAlias}`);
       const contractInstance = await this.appManagerWrapper.setImplementation(contractClass, contractAlias);
       log.info(`Uploaded ${contractName} at ${contractInstance.address}`);
-      this.networkPackage.contracts[contractAlias] = contractInstance.address;
+      this.networkPackage.contracts[contractAlias] = {
+        address: contractInstance.address,
+        bytecode: contractClass.bytecode
```
Comment (facuspagnuolo) [inline src/models/NetworkAppController.js]: what about storing a hash of the bytecode here instead of storing all of it? it will improve the readability of the json file

File: src/models/NetworkAppController.js [hunk 2]
```diff
@@ -152,7 +159,7 @@ export default class NetworkAppController {
     const networkStdlib = this.networkPackage.stdlib;
     const hasNetworkStdlib = !_.isEmpty(networkStdlib);
     const hasCustomDeploy = hasNetworkStdlib && networkStdlib.customDeploy;
-    const customDeployMatches = hasCustomDeploy && networkStdlib.name === this.package.stdlib.name;
+    const customDeployMatches = hasCustomDeploy && networkStdlib.name === this.package.stdlib.name && networkStdlib.version === this.package.stdlib.version;
```
Comment (facuspagnuolo) [inline src/models/NetworkAppController.js]: we can extract these behaviors to some functions like `hasSameNameAndVersion` or so

File: src/models/NetworkAppController.js [hunk 3]
```diff
@@ -161,9 +168,69 @@ export default class NetworkAppController {
...
+    return stdlib.hasContract(contractAlias);
+  }
+
+  isContractDefined(contractAlias) {
+    return this.isApplicationContract(contractAlias) || this.isStdlibContract(contractAlias);
+  }
+
+  isContractDeployed(contractAlias) {
+    return !this.isApplicationContract(contractAlias) || !_.isEmpty(this.networkPackage.contracts[contractAlias]);
+  }
```
Comment (facuspagnuolo) [inline src/models/NetworkAppController.js]: I'm starting to think that this controller is growing a lot and we may want to split it into a hierarchy in a short future

File: src/models/NetworkAppController.js [hunk 4]
```diff
@@ -161,9 +168,69 @@ export default class NetworkAppController {
...
 
     // TODO: Check that package version matches the requested one
+    // TODO: Do not invoke setStdlib if matches existing one
     log.info(`Connecting to public deployment of ${this.package.stdlib.name} in ${this.network}`);
     const stdlibAddress = StdlibProvider.from(this.package.stdlib.name, this.network);
     await this.appManagerWrapper.setStdlib(stdlibAddress);
     this.networkPackage.stdlib = { address: stdlibAddress, ... this.package.stdlib };
   }
+
+  checkContracts(throwIfFail = false) {
```
Comment (facuspagnuolo) [inline src/models/NetworkAppController.js]: I would try to be more explicit here, it is not clear what we are checking to me. Maybe we can rename this method to `checkDeployedContractsHaveNotChanged` or so

File: src/models/NetworkAppController.js [hunk 5]
```diff
@@ -161,9 +168,69 @@ export default class NetworkAppController {
...
+      msg = `Contracts ${contractsMissing.join(', ')} are not deployed.`;
+    } else if (!_.isEmpty(contractsChanged)) {
+      msg = `Contracts ${contractsChanged.join(', ')} have changed since the last deploy.`;
+    }
+
+    if (msg && throwIfFail) throw new Error(msg);
+    else if (msg) log.info(msg);    
+  }
+
+  checkContract(contractAlias, throwIfFail = false) {
```
Comment (facuspagnuolo) [inline src/models/NetworkAppController.js]: same here

File: src/models/stdlib/Stdlib.js [hunk 6]
```diff
@@ -22,6 +23,11 @@ export default class Stdlib {
     this._packageJson = fs.parseJson(filename)
     return this._packageJson
   }
+
+  hasContract(alias) {
+    if (!this.getPackage().contracts) return false;
+    return !_.isEmpty(this.getPackage().contracts[alias]);
```
Comment (facuspagnuolo) [inline src/models/stdlib/Stdlib.js]: We should modify the Object prototype and stop using lodash 🙏

Comment (spalladino) [reply src/models/stdlib/Stdlib.js]: We are going to have a heated discussion I'm afraid. I love lodash, and have a deeply rooted hate for modifying prototypes (probably because of several years of monkeypatching metaclasses in Ruby).

Comment (spalladino) [reply src/models/stdlib/Stdlib.js]: How about we switch to Clojure, which includes all lodash-like methods in its stdlib?

File: src/models/NetworkAppController.js (hunk 1 above)
Comment (spalladino) [reply src/models/NetworkAppController.js]: I was in doubt about that. On one hand it does improve readability, on the other it allows you to reconstruct a deployment from scratch _without_ needing to have a separate json file with the bytecode. However, we are not using it for anything for now.

File: src/models/NetworkAppController.js (hunk 3 above)
Comment (spalladino) [reply src/models/NetworkAppController.js]: Agree. But after EthBA :-P

**Comment by spalladino** [comment]
@facuspagnuolo fixed most comments, and changed bytecode to bytecodeHash in a separate commit. If you accept the PR, please rebase and don't squash, so the commit with the bytecode hash change is separate and can be reverted in the future if necessary.
